#Goal : say Hi and show the repo name
name: Hello Dosto
on:
  workflow_dispatch:
    

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello Dosto"
      - name: greet in english
        run: echo "Welcome"

  repo_name:
    needs: greet
    runs-on: ubuntu-latest
    steps:
      - name: repo name
        run: echo " ${{ github.event.repository.name }}"
      
